### ISSUE TITLE
infografia 

### ISSUE THREAD

**Issue by RaelRGB** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-RAEL12345#1]
[Rael infografia Gestion de proyectos de software.pdf](https://github.com/user-attachments/files/16753134/Rael.infografia.Gestion.de.proyectos.de.software.pdf)

**Comment by Luz1727** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
